import {localizeSystemMessage,t,formatDateTime,formatNumber,getLocale,pluralKey} from '../../i18n';
import {lazy,Suspense,useCallback,useEffect,useLayoutEffect,useRef,useState} from 'react';
import {Search,ArrowLeft,ArrowRight,Star,Paperclip,Reply,LockKeyhole,ChevronDown,Users,Plus,FileText,ExternalLink,Download} from 'lucide-react';
import {api} from '../../lib/api';
import {accountStore,offlineEnabled} from '../../lib/storage';
import {Empty,Loading,ErrorNotice,formatDate,initials,Modal,newId} from '../../components/ui';
import BlockContact from '../../components/BlockContact';
import Attachment from './Attachment';
import {subjectGroups} from './subjectGroups';
import DeliveryStatus, { type Delivery } from './DeliveryStatus';
import type {Conversation,Message,User,ComposeSeed,Draft} from './types';
const Composer=lazy(()=>import('./Composer'));
type Page={conversations?:Conversation[];messages?:Message[];hasMore:boolean;nextCursor:string|null};
function accountEmail(user:User){return String(user.email||user.primaryEmail||'')}
const folderLabels:Record<string,string>={inbox:'m_94835ea2fcf7',sent:'m_c16bc82bf1f0',drafts:'m_f592e6a4db3c',favorites:'m_7a1f2a83aca9',archive:'m_66f4804ee23d',spam:'m_94a9eac404c8',trash:'m_c560122ac470'};
const filterLabels:Record<string,string>={all:'m_a52ace420f21',unread:'m_1b9f384c1436',attachments:'m_634de1147750',favorites:'m_7a1f2a83aca9'};
const emptyCopy:Record<string,[import('../../i18n').MessageKey,import('../../i18n').MessageKey]>={inbox:['empty.inbox','empty.inboxHelp'],sent:['empty.sent','empty.sentHelp'],drafts:['empty.drafts','empty.draftsHelp'],archive:['empty.archive','empty.archiveHelp'],spam:['empty.spam','empty.spamHelp'],trash:['empty.trash','empty.trashHelp'],favorites:['empty.favorites','empty.favoritesHelp']};
function folderLabel(value:string){const key=folderLabels[value];return key?t(key as Parameters<typeof t>[0]):t("m_617ddd6bfe90")}
export default function Workspace({user,folder,refresh,composeSeed,onCompose,onNotice}:{user:User;folder:string;refresh:number;composeSeed:ComposeSeed|null;onCompose:(s:ComposeSeed|null)=>void;onNotice:(s:string,kind?:'status')=>void}){
 const seenMail=useRef<Map<string,string>>(new Map()),mailBaseline=useRef(false);
 const viewEpoch=useRef(0),readEpoch=useRef(0),decryptEpoch=useRef(0),listCursor=useRef<string|undefined>(),cursorBack=useRef<(string|undefined)[]>([]);
 const [draftSavedSignal,setDraftSavedSignal]=useState(0),[draftNotice,setDraftNotice]=useState('');const listLoading=useRef(false);
 const timelineScroll=useRef<{id?:string;top?:number;bottom?:boolean}|null>(null);
 const [historyNewer,setHistoryNewer]=useState(false),[updatesWaiting,setUpdatesWaiting]=useState(false);
 function invalidateView(){timelineScroll.current=null;viewEpoch.current++;readEpoch.current++;decryptEpoch.current++;detailAbort.current?.abort();setDecrypted(null);setDecrypting(false);setFullView(null);setDelivery(null);setOlderBusy(false)}
 useEffect(()=>()=>{viewEpoch.current++;readEpoch.current++;decryptEpoch.current++;detailAbort.current?.abort()},[]);
 const [separate,setSeparate]=useState<ComposeSeed|null>(null);
 const [filter,setFilter]=useState('all'),[query,setQuery]=useState(''),[debounced,setDebounced]=useState(''),[page,setPage]=useState<Page>({hasMore:false,nextCursor:null}),[loading,setLoading]=useState(true),[error,setError]=useState(''),[selected,setSelected]=useState<string|null>(null),[detail,setDetail]=useState<{conversation:Conversation;messages:Message[];pagination:{hasMore:boolean;page:number}}|null>(null),[reading,setReading]=useState<Message|null>(null),[detailError,setDetailError]=useState(''),[detailLoading,setDetailLoading]=useState(false),[version,setVersion]=useState(0),[fullView,setFullView]=useState<Message|null>(null),[delivery,setDelivery]=useState<Delivery|null>(null),[decrypting,setDecrypting]=useState(false),[decrypted,setDecrypted]=useState<{id:string;subject:string;text:string;attachments:any[]}|null>(null),[olderBusy,setOlderBusy]=useState(false),[encryptedDrafts,setEncryptedDrafts]=useState<any[]>([]);
 useEffect(()=>{const clear=()=>{decryptEpoch.current++;setDecrypted(null);setDecrypting(false)};window.addEventListener('phonemail:keys-locked',clear);return()=>window.removeEventListener('phonemail:keys-locked',clear)},[]);
 const [cacheNote,setCacheNote]=useState(''),[syncNote,setSyncNote]=useState(''),[localDrafts,setLocalDrafts]=useState<any[]>([]),[offlinePolicy,setOfflinePolicy]=useState(0);
 useEffect(()=>{const policy=()=>setOfflinePolicy(v=>v+1);window.addEventListener('phonemail:offline-policy',policy);return()=>window.removeEventListener('phonemail:offline-policy',policy)},[]);
 useEffect(()=>{if(!offlineEnabled(user.id))return;const ctrl=new AbortController();let timer:ReturnType<typeof setTimeout>;let failures=0;async function tick(){let delay=60000;try{if(navigator.onLine&&document.visibilityState==='visible'){const {syncAccount}=await import('../../lib/sync');const result=await syncAccount(user.id,ctrl.signal);if(ctrl.signal.aborted)return;failures=0;setSyncNote('');if(result.changed)setVersion(v=>v+1);if(result.more)delay=1500;}}catch(e:any){if(!ctrl.signal.aborted){setSyncNote(t('cache.outdated',{error:e.message}));delay=Math.max(e.retryAfter||0,Math.min(300000,15000*2**Math.min(++failures,5)));}}if(!ctrl.signal.aborted)timer=setTimeout(tick,delay)}void tick();return()=>{ctrl.abort();clearTimeout(timer)}},[user.id,offlinePolicy]);
 useEffect(()=>{if(folder==='drafts')void accountStore(user.id).all('local-draft').then(rows=>setLocalDrafts(rows.map(r=>({key:r.key,...r.value as object})))).catch(e=>setError(e.message))},[folder,version]);
 const abort=useRef<AbortController>(),detailAbort=useRef<AbortController>(),historyRef=useRef<HTMLDivElement>(null),swipe=useRef(0);
 useEffect(()=>{const id=setTimeout(()=>setDebounced(query.trim()),300);return()=>clearTimeout(id)},[query]);
 const endpoint=useCallback((cursor?:string)=>{const params=new URLSearchParams({limit:'30'});if(cursor)params.set('cursor',cursor);if(debounced.length>=2){params.set('q',debounced);return `/search/messages?${params}`}if(folder==='home'||folder==='favorites'){params.set('filter',folder==='favorites'?'favorites':filter);return `/conversations?${params}`}return `/conversations/mailbox/${folder}?${params}`},[folder,filter,debounced]);
 const load=useCallback(async(more=false,background=false)=>{
  if(background&&listLoading.current)return false;listLoading.current=true;
  abort.current?.abort();const ctrl=new AbortController();abort.current=ctrl;if(!background)setLoading(true);setError('');setCacheNote('');
  const nextCursor=more?page.nextCursor||undefined:listCursor.current;
  const cacheKey=endpoint(nextCursor);
  try {
    const result=await api<Page>(cacheKey,{signal:ctrl.signal});if(ctrl.signal.aborted)return;
    if(!nextCursor&&folder==='home'&&filter==='all'&&debounced.length<2){const snapshots=new Map((result.conversations||[]).map(c=>[c.id,c.lastMessage?.id||'']));let changed=0;if(mailBaseline.current){for(const c of result.conversations||[])if(c.lastMessage?.senderEmail!==accountEmail(user)&&c.lastMessage?.id&&seenMail.current.get(c.id)!==c.lastMessage.id)changed++;}seenMail.current=snapshots;mailBaseline.current=true;try{if(changed&&localStorage.getItem('phonemail.web-notices:'+user.id)==='true')onNotice(pluralKey(changed,'notice.newMailOne','notice.newMail'),'status')}catch{/* No announcement opt-in without readable preference. */}}
    if(more)cursorBack.current.push(listCursor.current);listCursor.current=nextCursor;setPage({...result,conversations:result.conversations?.filter((c,i,a)=>a.findIndex(x=>x.id===c.id)===i),messages:result.messages?.filter((m,i,a)=>a.findIndex(x=>x.id===m.id)===i)});setUpdatesWaiting(false);
    await accountStore(user.id).put('cache',cacheKey,{page:result,savedAt:Date.now()}).catch(()=>setCacheNote(t("m_807359dbd5f3")));return true;
  } catch(e:any) {
    if(e.name!=='AbortError'){
      setError(e.message||t("m_94649be5d872"));
      if(!more&&(e.status===0||e.status>=500)){
        const cached=await accountStore(user.id).get<{page:Page;savedAt:number}>('cache',cacheKey).catch(()=>undefined);
        if(cached&&!ctrl.signal.aborted){setPage(cached.page);setCacheNote(t('cache.saved',{time:formatDateTime(cached.savedAt)}));}
      }
    }
  } finally {if(abort.current===ctrl){listLoading.current=false;setLoading(false)}}
 },[endpoint,page.nextCursor,user.id]);
 useEffect(()=>{listCursor.current=undefined;cursorBack.current=[];setPage({hasMore:false,nextCursor:null});void load();return()=>abort.current?.abort()},[endpoint]);
 useEffect(()=>{if(listCursor.current){setUpdatesWaiting(true);return}void load()},[refresh,version]);
 useEffect(()=>{if(folder==='drafts')return;let timer:ReturnType<typeof setTimeout>;const refreshVisible=()=>{if(document.visibilityState==='visible'&&navigator.onLine&&!composeSeed){if(listCursor.current)setUpdatesWaiting(true);else void load();}};const tick=()=>{refreshVisible();timer=setTimeout(tick,60000)};timer=setTimeout(tick,60000);document.addEventListener('visibilitychange',refreshVisible);return()=>{clearTimeout(timer);document.removeEventListener('visibilitychange',refreshVisible)}},[endpoint,composeSeed]);
 const draftReload=useRef(load);draftReload.current=load;
 const requestDraftRefresh=useRef<()=>void>(()=>{}),savedDraftPending=useRef(false);
 useEffect(()=>{
  if(folder!=='drafts'||debounced.length>=2){setDraftNotice('');return}
  let active=true,running=false,again=false,timer:ReturnType<typeof setTimeout>;const ctrl=new AbortController();
  async function refreshDrafts(){
   if(!active)return;if(running){again=true;return}running=true;clearTimeout(timer);
   try{
    const local=await accountStore(user.id).all('local-draft');if(!active)return;setLocalDrafts(local.map(r=>({key:r.key,...r.value as object})));
    let updated=!navigator.onLine;
    if(navigator.onLine&&document.visibilityState==='visible'){
     const ordinary=await draftReload.current(false,true);
     const encrypted=await api<{drafts:any[]}>('/e2ee/drafts',{signal:ctrl.signal});if(!active)return;setEncryptedDrafts(encrypted.drafts);updated=!!ordinary;
    }
    if(active&&savedDraftPending.current&&updated){setDraftNotice(t(navigator.onLine?'composer.draftsUpdated':'composer.localDraftUpdated'));savedDraftPending.current=false;if(listCursor.current)setUpdatesWaiting(true)}
   }catch(e:any){if(active&&e.name!=='AbortError')setError(e.message)}
   finally{running=false;if(active){if(again){again=false;timer=setTimeout(()=>void refreshDrafts(),100)}else if(navigator.onLine&&document.visibilityState==='visible')timer=setTimeout(()=>void refreshDrafts(),4000)}}
  }
  const wake=()=>{clearTimeout(timer);if(navigator.onLine&&document.visibilityState==='visible')void refreshDrafts()};
  requestDraftRefresh.current=()=>void refreshDrafts();void refreshDrafts();
  document.addEventListener('visibilitychange',wake);window.addEventListener('online',wake);window.addEventListener('offline',wake);
  return()=>{active=false;ctrl.abort();clearTimeout(timer);requestDraftRefresh.current=()=>{};document.removeEventListener('visibilitychange',wake);window.removeEventListener('online',wake);window.removeEventListener('offline',wake)};
 },[folder,endpoint,user.id]);
 useEffect(()=>{if(!draftSavedSignal)return;savedDraftPending.current=true;requestDraftRefresh.current()},[draftSavedSignal]);
 useEffect(()=>{invalidateView();setSelected(null);setDetail(null);setReading(null)},[folder]);
 async function open(id:string,messageId?:string){invalidateView();setHistoryNewer(false);detailAbort.current?.abort();const ctrl=new AbortController();detailAbort.current=ctrl;setSelected(id);setDetailLoading(true);setDetailError('');setReading(null);setDetail(null);setDecrypted(null);try{const r=await api<any>(`/conversations/${id}?pageSize=20`,{signal:ctrl.signal});if(ctrl.signal.aborted)return;setDetail(r);await accountStore(user.id).put('cache','conversation:'+id,{value:r,savedAt:Date.now()}).catch(()=>{});if(ctrl.signal.aborted)return;const target=r.messages.find((m:Message)=>m.id===messageId)||r.messages.at(-1);if(target)await read(target,ctrl.signal)}catch(e:any){if(e.name!=='AbortError'&&!ctrl.signal.aborted){setDetailError(e.message);if(e.status===0||e.status>=500){const cached=await accountStore(user.id).get<{value:any;savedAt:number}>('cache','conversation:'+id).catch(()=>undefined);if(cached&&!ctrl.signal.aborted){setDetail(cached.value);setDetailError(t('cache.saved',{time:formatDateTime(cached.savedAt)}));const target=cached.value.messages.find((m:Message)=>m.id===messageId)||cached.value.messages.at(-1);if(target)await read(target,ctrl.signal)}}}}finally{if(!ctrl.signal.aborted)setDetailLoading(false)}}
 async function read(m:Message,signal?:AbortSignal){const epoch=++readEpoch.current,view=viewEpoch.current;decryptEpoch.current++;setDecrypting(false);setReading(m);setDecrypted(null);const owns=()=>epoch===readEpoch.current&&view===viewEpoch.current&&!signal?.aborted;try{const r=await api<{message:Message}>(`/conversations/${m.conversationId}/messages/${m.id}`,{signal});if(!owns())return;await accountStore(user.id).put('cache','message:'+m.id,{value:r.message,savedAt:Date.now()}).catch(()=>{});if(!owns())return;setReading({...r.message,isRead:true});setDetail(d=>d?{...d,messages:d.messages.map(x=>x.id===m.id?{...r.message,isRead:true}:x)}:d);if(!r.message.isRead)await api(`/conversations/${m.conversationId}/messages/${m.id}/state`,{method:'PATCH',body:JSON.stringify({isRead:true})});}catch(e:any){if(e.name!=='AbortError'&&owns()){setDetailError(e.message);if(e.status===0||e.status>=500){const cached=await accountStore(user.id).get<{value:Message;savedAt:number}>('cache','message:'+m.id).catch(()=>undefined);if(cached&&owns()){setReading(cached.value);setDetailError(t('cache.saved',{time:formatDateTime(cached.savedAt)}))}}}}}
 function captureHistory(){const el=historyRef.current;if(!el)return null;const bounds=el.getBoundingClientRect();const anchor=Array.from(el.querySelectorAll<HTMLElement>('[data-message]')).find(node=>node.getBoundingClientRect().bottom>bounds.top);return anchor?{id:anchor.dataset.message,top:anchor.getBoundingClientRect().top}:null}
 useLayoutEffect(()=>{const pending=timelineScroll.current,el=historyRef.current;timelineScroll.current=null;if(!pending||!el)return;if(pending.bottom){el.scrollTop=el.scrollHeight;return}const anchor=Array.from(el.querySelectorAll<HTMLElement>('[data-message]')).find(node=>node.dataset.message===pending.id);if(anchor&&pending.top!==undefined)el.scrollTop+=anchor.getBoundingClientRect().top-pending.top},[detail?.messages]);
 async function older(){if(!detail||olderBusy)return;const epoch=viewEpoch.current,id=detail.conversation.id;setOlderBusy(true);try{const r=await api<any>(`/conversations/${id}/messages?page=${detail.pagination.page+1}&pageSize=20`,{signal:detailAbort.current?.signal});if(epoch!==viewEpoch.current)return;timelineScroll.current=captureHistory();setDetail(d=>d?.conversation.id===id?{...d,messages:orderedMessages([...r.messages,...d.messages]).slice(0,60),pagination:r.pagination}:d);setHistoryNewer(true)}catch(e:any){if(epoch===viewEpoch.current&&e.name!=='AbortError')setDetailError(e.message)}finally{if(epoch===viewEpoch.current)setOlderBusy(false)}}
 const latestDetail=useRef(detail);latestDetail.current=detail;
 // Reuse mailbox refreshes; do not add another polling loop. A bounded older
 // window stays intact until its reader explicitly requests latest history.
 useEffect(()=>{if(!detail||historyNewer||olderBusy||!navigator.onLine||document.visibilityState!=='visible')return;const id=detail.conversation.id,epoch=viewEpoch.current,ctrl=new AbortController();
  void api<NonNullable<typeof detail>>(`/conversations/${id}?pageSize=20`,{signal:ctrl.signal}).then(latest=>{if(ctrl.signal.aborted||epoch!==viewEpoch.current)return;const previous=latestDetail.current;if(!previous||previous.conversation.id!==id)return;const added=latest.messages.filter(m=>!previous.messages.some(old=>old.id===m.id));if(!added.length)return;const el=historyRef.current,atBottom=!!el&&el.scrollHeight-el.scrollTop-el.clientHeight<80;const merged=orderedMessages([...previous.messages,...latest.messages]);const disconnected=!latest.messages.some(m=>previous.messages.some(old=>old.id===m.id));if((disconnected||merged.length>60)&&!atBottom){setHistoryNewer(true);return}timelineScroll.current=atBottom?{bottom:true}:captureHistory();setDetail(disconnected||merged.length>60?latest:{...previous,conversation:latest.conversation,messages:merged})}).catch(e=>{if(e.name!=='AbortError'&&epoch===viewEpoch.current)setDetailError(e.message)});return()=>ctrl.abort();
 },[page,olderBusy,historyNewer]);
 async function state(m:Message,patch:Partial<Message>){if(patch.folder==='trash'&&!window.confirm(t('mail.confirmTrash')))return;try{await api(`/conversations/${m.conversationId}/messages/${m.id}/state`,{method:'PATCH',body:JSON.stringify(patch)});setReading(r=>r?.id===m.id?{...r,...patch}:r);setFullView(r=>r?.id===m.id?{...r,...patch}:r);setDetail(d=>d?{...d,messages:d.messages.map(x=>x.id===m.id?{...x,...patch}:x)}:d);setVersion(v=>v+1)}catch(e:any){setDetailError(e.message)}}
 function reply(m:Message){const mine=accountEmail(user);const all=m.recipients||[];const to=[...new Set([m.senderEmail,...all.filter(r=>r.role==='to').map(r=>r.email)].filter(x=>x&&x!==mine))],cc=all.filter(r=>r.role==='cc'&&r.email!==mine&&!to.includes(r.email)).map(r=>r.email);onCompose({key:newId(),to,cc,subject:m.subject,conversationId:m.conversationId,replyToId:m.id,encrypted:m.contentFormat==='openpgp-v1',locked:true})}
 function newMessage(){if(!detail||!current)return;const encrypted=current.contentFormat==='openpgp-v1';const domain=accountEmail(user).split('@')[1];const others=detail.conversation.members.filter(x=>x!==accountEmail(user));const external=others.some(x=>x.split('@')[1]!==domain);if(encrypted||external){setSeparate({key:newId(),to:others,encrypted});return}const first=!detail.pagination.hasMore?detail.messages[0]:undefined;const canonical=first?.senderEmail===accountEmail(user)&&first.contentFormat!=='openpgp-v1'&&first.recipients?.length;onCompose({key:newId(),to:canonical?first.recipients!.filter(r=>r.role==='to').map(r=>r.email):others,cc:canonical?first.recipients!.filter(r=>r.role==='cc').map(r=>r.email):[],conversationId:detail.conversation.id,locked:true,atomicThread:!!canonical})}

 async function openFull(m:Message){const epoch=viewEpoch.current;try{const r=await api<{message:Message}>(`/conversations/${m.conversationId}/messages/${m.id}`);if(epoch!==viewEpoch.current)return;setFullView(r.message);await accountStore(user.id).put('cache','message:'+m.id,{value:r.message,savedAt:Date.now()}).catch(()=>{})}catch(e:any){if(epoch!==viewEpoch.current)return;setDetailError(e.message);if(e.status===0||e.status>=500){const cached=await accountStore(user.id).get<{value:Message}>('cache','message:'+m.id).catch(()=>undefined);if(cached&&epoch===viewEpoch.current)setFullView(cached.value)}}}
 async function decrypt(m:Message){const epoch=++decryptEpoch.current,view=viewEpoch.current;setDecrypting(true);setDetailError('');try{const service=await import('../security/service');const value=await service.decryptMessage(user.id,m.id);if(epoch===decryptEpoch.current&&view===viewEpoch.current&&service.isUnlocked(user.id))setDecrypted({id:m.id,...value})}catch(e:any){if(epoch===decryptEpoch.current&&view===viewEpoch.current)setDetailError(e.message)}finally{if(epoch===decryptEpoch.current)setDecrypting(false)}}
 async function openDraft(m:Message){try{const {draft}=await api<{draft:Draft}>(`/drafts/${m.id}`);onCompose({key:newId(),draft,to:draft.to,cc:draft.cc,subject:draft.subject,body:draft.body})}catch(e:any){onNotice(e.message)}}
 async function deliveryDetails(m:Message){const epoch=viewEpoch.current;try{const r=await api<any>(`/conversations/${m.conversationId}/messages/${m.id}/delivery`);if(epoch===viewEpoch.current)setDelivery(r.delivery)}catch(e:any){if(epoch===viewEpoch.current)setDetailError(e.message)}}
 const conversations=page.conversations||[],messages=page.messages||[],title=debounced.length>=2?t("m_e978b00de465"):folder==='home'?t("m_903532e03397"):folderLabel(folder),name=detail?.conversation.members.filter(x=>x!==accountEmail(user)).join(', ')||t("m_ccca18175753");
 useEffect(()=>{const el=historyRef.current;if(el)el.scrollTop=el.scrollHeight},[detail?.conversation.id]);
 const current=detail?.messages.at(-1)||reading;
 function forward(m:Message){if(m.contentFormat==='openpgp-v1')return;onCompose({key:newId(),subject:t('forward.subject',{subject:m.subject}),body:t('forward.body',{sender:m.senderEmail,date:formatDateTime(m.createdAt),subject:m.subject,body:m.body}),forwarded:true})}

 return <div className={`mail-workspace ${selected?'has-selection':''}`}><section className="mail-list-pane" aria-label={title}><div className="list-heading"><div><span className="eyebrow">{t("m_4757ec62d71d")}</span><h1>{title}<span className="heading-dot">.</span></h1></div><span className="date-label">{formatDate(new Date().toISOString(),true)}</span></div><label className="search-field"><Search size={19}/><input type="search" placeholder={t("m_031e345cc157")} value={query} onChange={e=>setQuery(e.target.value)} aria-label={t("m_031e345cc157")} maxLength={200}/><kbd>⌕</kbd></label>{debounced.length>=2&&<p className="search-help">{t("m_4d596336dbae")}</p>}<div className="filter-row" role="group" aria-label={t("m_0f525e6dfeb2")}>{['all','unread','attachments','favorites'].map(f=><button key={f} className={filter===f?'selected':''} onClick={()=>setFilter(f)} disabled={folder!=='home'&&folder!=='favorites'}>{f==='attachments'?<Paperclip size={13}/>:null}{t(filterLabels[f] as Parameters<typeof t>[0])}</button>)}</div><div className="list-meta"><span>{loading?t("m_b7d2eeadf529"):`${conversations.length?pluralKey(conversations.length,'m_41917cecee7a','m_2889fc6b0647'):pluralKey(messages.length,'m_011052fed019','m_d7b79bfdb6b9')}${page.hasMore?' · '+t("m_5539fa781ac0"):''}`}</span><span>{t("m_baa7bfd402ff")}<ChevronDown size={12}/></span></div>
 <div className="message-list" onTouchStart={e=>{swipe.current=e.currentTarget.scrollTop===0?e.touches[0].clientY:0}} onTouchEnd={e=>{if(swipe.current&&e.changedTouches[0].clientY-swipe.current>90&&!loading)void load();swipe.current=0}}>{folder==='drafts'&&draftNotice&&<p className="search-help" role="status">{draftNotice}</p>}{updatesWaiting&&<p role="status">{t('mail.updatesWaiting')}<button onClick={()=>{listCursor.current=undefined;cursorBack.current=[];void load()}}>{t('mail.newest')}</button></p>}{cursorBack.current.length>0&&<button className="load-more" disabled={loading} onClick={()=>{listCursor.current=cursorBack.current.pop();void load()}}>{t('mail.previousPage')}</button>}{cacheNote&&<p className="search-help" role="status">{localizeSystemMessage(cacheNote)}</p>}{syncNote&&<p className="search-help" role="status">{localizeSystemMessage(syncNote)}</p>}{folder==='drafts'&&localDrafts.map(d=><button className="message-row" key={d.key} onClick={()=>onCompose({key:d.key,...d,localRecovery:true,draft:d.draft,to:d.to,cc:d.cc})}><span className="avatar"><FileText size={18}/></span><span className="row-content"><strong>{d.subject||t("m_fdcd01fae2f3")}</strong><span className="row-preview">{t("m_1e4ea9db1ac6")}</span></span></button>)}{error&&<ErrorNotice message={error} retry={()=>void load()}/>} {loading&&!messages.length&&!conversations.length?<Loading label={t("m_4a227c66a0e8")}/>:null}{!loading&&!error&&!conversations.length&&!messages.length&&!(folder==='drafts'&&(encryptedDrafts.length||localDrafts.length))&&<Empty title={query?t('m_bf3cda441288'):t(emptyCopy[folder]?.[0]||'m_f6dc2bac6c5f')}><p>{query?t('m_e7f9b6491c29'):t(emptyCopy[folder]?.[1]||'m_aa1214a364c2')}</p><button className="button primary" onClick={()=>onCompose({key:newId()})}><Plus size={17}/>{t("m_258150cb3ee4")}</button></Empty>}
 {conversations.map((c,i)=>{const others=c.members.filter(x=>x!==accountEmail(user));return <button key={c.id} className={`message-row ${selected===c.id?'selected':''} ${c.unreadCount?'unread':''}`} onClick={()=>void open(c.id)}><span className={`avatar tone-${i%4}`}>{c.kind==='group'?<Users size={19}/>:initials(others[0]||'P')}</span><span className="row-content"><span className="row-top"><strong>{others.join(', ')||t("m_ccca18175753")}</strong><time>{formatDate(c.lastMessage?.createdAt||c.updatedAt,true)}</time></span><span className="row-subject">{!!(c.hasAttachments||c.lastMessage?.attachments?.length||c.lastMessage?.attachmentCount)&&<Paperclip size={14} aria-label={t('mail.hasAttachments')}/>} {c.lastMessage?.subject||t("m_396c946f0c79")}{c.unreadCount>0&&<span className="unread-dot"/>}</span><span className="row-preview">{c.lastMessage?.body||t("m_10ef19f37b01")}{c.unreadCount>0&&<b className="count-badge">{formatNumber(c.unreadCount)}</b>}</span></span></button>})}
 {messages.map((m,i)=><button key={m.id} className={`message-row ${reading?.id===m.id?'selected':''} ${!m.isRead?'unread':''}`} onClick={()=>void(m.entityType==='draft'?openDraft(m):open(m.conversationId,m.id))}><span className={`avatar tone-${i%4}`}>{m.entityType==='draft'?<FileText size={18}/>:initials(m.senderEmail)}</span><span className="row-content"><span className="row-top"><strong>{m.entityType==='draft'?t("m_ebf12ef47cf5"):m.senderEmail}</strong><time>{formatDate(m.createdAt,true)}</time></span><span className="row-subject">{!!(m.attachments?.length||m.attachmentCount)&&<Paperclip size={14} aria-label={t('mail.hasAttachments')}/>} {m.subject||t("m_53f5067dc8a5")}{m.isFavorite&&<Star size={13}/>}</span><span className="row-preview">{m.body||m.snippet||t("m_268b37608588")}</span></span></button>)}
 {folder==='drafts'&&encryptedDrafts.map(d=><button className="message-row" key={d.id} onClick={()=>onCompose({key:newId(),encrypted:true,draft:{...d,subject:'',body:'',to:[],cc:[]}})}><span className="avatar"><LockKeyhole size={17}/></span><span className="row-content"><strong>{t("m_e4b84cb7046f")}</strong><span className="row-preview">{t('draft.revision',{revision:formatNumber(d.revision)})}</span></span></button>)}
 {page.hasMore&&<button className="load-more" disabled={loading} onClick={()=>void load(true)}>{loading?t("m_ba3bbbe10d8b"):t("m_ac8991ef0101")}<ChevronDown size={16}/></button>}</div><div className="list-bottom"><LeafMark/> {t("m_3ab08fe8568a")}</div></section>
 <section className="reading-pane" aria-label={t("m_dde5ae89d4de")}>{!selected?<div className="reading-welcome"><div className="welcome-art"><img src="/favicon.svg" alt=""/><span className="orbit one"/><span className="orbit two"/><span className="orbit three"/></div><span className="eyebrow">{t("m_1453ccdf9be7")}</span><h2>{t('welcome.headline')}</h2><p>{t("m_a8c933f5357d")}<br/>{t("m_38d4752ec95f")}</p><button className="button outline" onClick={()=>onCompose({key:newId()})}>{t("m_0b93776166a9")}<ArrowRight size={17}/></button><span className="welcome-footnote">{t("m_b501899e0a68")}</span></div>:<><header className="conversation-heading"><button className="icon-button back-button" aria-label={t("m_d456fc756644")} onClick={()=>{invalidateView();setSelected(null);setDetail(null);setReading(null)}}><ArrowLeft size={19}/></button><span className="avatar small">{detail?.conversation.kind==='group'?<Users size={16}/>:initials(name)}</span><div><h2>{name}</h2><span>{detail?.conversation.kind==='group'?t("m_b6aebd2846a4"):t("m_abe772881cdd")} {t("m_fbd780ed3fe3")}</span></div></header>{detailError&&<ErrorNotice message={detailError}/>} {detailLoading?<Loading label={t("m_12a7ad1d379e")}/>:null}
 {detail&&<><div className="mobile-history conversation-timeline" ref={historyRef} tabIndex={0} aria-label={t("m_dde5ae89d4de")}>
 {historyNewer&&<button className="load-more latest-history" onClick={()=>void open(detail.conversation.id)}>{t('mail.latestHistory')}</button>}{detail.pagination.hasMore&&<button className="load-more" onClick={()=>void older()} disabled={olderBusy}>{olderBusy?t("m_ba3bbbe10d8b"):t("m_f17671d83db0")}</button>}
 {subjectGroups(orderedMessages(detail.messages),decrypted).map(group=><section className="subject-group" key={group.id} aria-labelledby={`subject-${group.id}`}><h3 className="subject-heading" id={`subject-${group.id}`}>{group.subject||t("m_53f5067dc8a5")}</h3>{group.messages.map(m=><article className={`bubble ${m.senderEmail===accountEmail(user)?'outgoing':''}`} key={m.id} data-message={m.id} aria-labelledby={[`sender-${m.id}`,`subject-${group.id}`].join(" ")}>
 <div className="bubble-heading"><span className="bubble-sender" id={`sender-${m.id}`}>{m.senderEmail===accountEmail(user)?`${t("m_08b041935798")} · ${m.senderEmail}`:m.senderEmail}</span><time dateTime={m.createdAt}>{formatDateTime(m.createdAt)}</time>{m.isFavorite&&<Star size={14} aria-label={t("m_7a1f2a83aca9")}/>}</div>
 {m.contentFormat==='openpgp-v1'&&decrypted?.id!==m.id?<div className="encrypted-placeholder"><LockKeyhole size={22}/><h4>{t("m_16217c15a3cd")}</h4><p>{t("m_125e91cdcce6")}</p><button className="button outline" disabled={decrypting} onClick={()=>void decrypt(m)}>{decrypting?t("m_aae578c4ac88"):t("m_e827ba9b6cd6")}</button></div>:<div className="safe-message-text">{decrypted?.id===m.id?decrypted.text:m.body}</div>}
 {m.contentFormat!=='openpgp-v1'&&(m.attachments||[]).map(a=><Attachment key={a.id} attachment={a}/>)}{decrypted?.id===m.id&&decrypted.attachments.map((a:any,i)=><button key={i} className="attachment" onClick={()=>downloadBytes(a.bytes||a.data,a.name,a.type)}><Paperclip size={17}/>{a.name}<Download size={15}/></button>)}
 {['trash','spam','archive'].includes(m.folder||'')&&<div className="message-folder-banner">{t('mail.folderBanner',{folder:folderLabel(m.folder||'')})}<button onClick={()=>void state(m,{folder:m.senderEmail===accountEmail(user)?'sent':'inbox'})}>{t("m_f26b91a3798e")}</button></div>}
 <div className="bubble-bottom"><button className="button quiet compact" aria-label={t("m_9bcfe35c7185",{value0:m.subject||t("m_2f77668a9dfb")})} onClick={()=>reply(m)}><Reply size={16}/>{t("m_c253f451bdd5")}</button><button className="icon-button" aria-label={t("m_b4b4cc5c5002")} onClick={()=>void openFull(m)}><ExternalLink size={16}/></button></div>
 <details className="bubble-actions"><summary>{t("mail.messageActions")}</summary><div className="bubble-recipients">{t("m_e38ec11fedb3")}{(m.recipients||[]).filter(r=>r.role==='to').map(r=>r.email).join(', ')}{m.recipients?.some(r=>r.role==='cc')&&<> {t("m_911f182a7f15")}{m.recipients.filter(r=>r.role==='cc').map(r=>r.email).join(', ')}</>}</div><div className="button-row">
 <button className="button quiet" aria-pressed={m.isFavorite} onClick={()=>void state(m,{isFavorite:!m.isFavorite})}>{m.isFavorite?t("m_5bc0aa08d678"):t("m_65b52e8c6521")}</button><button className="button quiet" onClick={()=>void state(m,{isRead:!m.isRead})}>{m.isRead?t("m_54b4e3f28dc5"):t("m_b49c9b6cdf43")}</button>{['archive','spam','trash'].map(folder=><button className="button quiet" key={folder} onClick={()=>void state(m,{folder})}>{folderLabel(folder)}</button>)}<button className="button quiet" onClick={()=>void deliveryDetails(m)}>{t("m_dbebda550bfb")}</button>{m.contentFormat!=='openpgp-v1'&&<button className="button quiet" onClick={()=>forward(m)}>{t('forward.action')}</button>}{m.senderEmail!==accountEmail(user)&&<BlockContact address={m.senderEmail}/>}</div></details>
 </article>)}</section>)}</div>
 <div className="thread-compose-bar"><button className="button primary" onClick={()=>current&&reply(current)} disabled={!current}><Reply size={17}/>{t("m_c253f451bdd5")}</button><button className="button outline" onClick={newMessage}><Plus size={17}/>{current?.contentFormat==='openpgp-v1'?t("m_398c73eb02af"):t("m_78f5975a5d70")}</button></div></>}
 </>}</section>
 {separate&&<Modal title={t("m_9fdc0079202f")} onClose={()=>setSeparate(null)}><p>{t("m_c77121287940")}</p><p>{separate.to?.join(', ')}</p><div className="button-row"><button className="button primary" onClick={()=>{onCompose(separate);setSeparate(null)}}>{t("m_5f54f388aa90")}</button><button className="button outline" onClick={()=>setSeparate(null)}>{t("m_73c533857ea9")}</button></div></Modal>}
 {composeSeed&&<Suspense fallback={<Loading label={t("m_cf25b47a2bd9")}/>}><Composer key={composeSeed.key} user={user} seed={composeSeed} onSaved={()=>setDraftSavedSignal(v=>v+1)} onClose={()=>onCompose(null)} onSent={()=>{onCompose(null);setVersion(v=>v+1);if(selected)void open(selected)}}/></Suspense>}
 {fullView&&<Modal title={fullView.subject||t("m_2f77668a9dfb")} onClose={()=>{decryptEpoch.current++;setDecrypted(null);setFullView(null)}} wide><p className="muted">{fullView.senderEmail} · {formatDate(fullView.createdAt)}</p><div className="button-row"><button className="button quiet" onClick={()=>void state(fullView,{isFavorite:!fullView.isFavorite})}>{fullView.isFavorite?t("m_5bc0aa08d678"):t("m_ea713ecd8537")}</button><button className="button quiet" onClick={()=>void state(fullView,{isRead:!fullView.isRead})}>{fullView.isRead?t("m_54b4e3f28dc5"):t("m_b49c9b6cdf43")}</button>{['archive','spam','trash'].map(folder=><button className="button quiet" key={folder} onClick={()=>void state(fullView,{folder})}>{folderLabel(folder)}</button>)}{['archive','spam','trash'].includes(fullView.folder||'')&&<button className="button quiet" onClick={()=>void state(fullView,{folder:fullView.senderEmail===accountEmail(user)?'sent':'inbox'})}>{t("m_a76e13b98392")}</button>}<button className="button quiet" onClick={()=>void deliveryDetails(fullView)}>{t("m_dbebda550bfb")}</button></div>{fullView.contentFormat==='openpgp-v1'&&decrypted?.id!==fullView.id?<button className="button primary" disabled={decrypting} onClick={()=>void decrypt(fullView)}>{t("m_e827ba9b6cd6")}</button>:<div className="safe-message-text">{decrypted?.id===fullView.id?decrypted.text:fullView.body}</div>}{(fullView.attachments||[]).map(a=><Attachment key={a.id} attachment={a}/>)}{decrypted?.id===fullView.id&&decrypted.attachments.map((a:any,i)=><button key={i} className="attachment" onClick={()=>downloadBytes(a.bytes,a.name,a.type)}><Paperclip size={17}/>{a.name}<Download size={15}/></button>)}<button className="button primary" onClick={()=>{reply(fullView);setFullView(null)}}><Reply size={17}/>{t("m_c253f451bdd5")}</button></Modal>}
 {delivery&&<Modal title={t("m_dbebda550bfb")} onClose={()=>setDelivery(null)}><p>{t("m_44d05df8d610")}</p><DeliveryStatus delivery={delivery}/></Modal>}
 </div>
}
function LeafMark(){return <svg width="15" height="15" viewBox="0 0 20 20" fill="none" stroke="currentColor"><path d="M4 16C-2 4 11 2 17 2c0 11-3 17-13 14Zm0 0L13 6"/></svg>}
function downloadBytes(data:any,name:string,type='application/octet-stream'){const bytes=data instanceof Uint8Array?data:new Uint8Array(data||[]);const url=URL.createObjectURL(new Blob([new Uint8Array(bytes)],{type}));const a=document.createElement('a');a.href=url;a.download=name.replace(/[\x00-\x1f/\\]/g,'_');a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}

function orderedMessages(messages:Message[]){return [...new Map(messages.map(message=>[message.id,message])).values()].sort((a,b)=>Date.parse(a.createdAt)-Date.parse(b.createdAt)||a.id.localeCompare(b.id))}
