import assert from 'node:assert/strict';
import test from 'node:test';
import {createIdentity,decryptMime,encryptMime,importIdentity,makeQrPayload,readQrPayload,validatePublicIdentity,type LocalIdentity} from '../src/vendor/e2ee/index';
import {PhoneMailE2eeClient,type CurrentPublicKey,type FingerprintTrustStore,type StoredTrust} from '../src/vendor/e2ee/client';
import {decodeMime} from '../src/features/security/mime';
const aliceId='11111111-1111-4111-8111-111111111111',bobId='22222222-2222-4222-8222-222222222222',draftId='33333333-3333-4333-8333-333333333333';
const passphrase='long independently stored test passphrase';
const identities=Promise.all([createIdentity(aliceId,passphrase),createIdentity(bobId,passphrase)]);
class Pins implements FingerprintTrustStore{values=new Map<string,StoredTrust[]>();async get(id:string){return this.values.get(id)?.at(-1);}async getHistory(id:string){return this.values.get(id)||[];}async set(pin:StoredTrust){this.values.set(pin.userId,[...(this.values.get(pin.userId)||[]),pin]);}async remove(id:string){this.values.delete(id);}}
const publicKey=(key:LocalIdentity):CurrentPublicKey=>({...key,encryptionKeyId:'',createdAt:new Date().toISOString()});
async function fixture(){const [alice,bob]=await identities;const pins=new Pins();const keys=new Map([alice,bob].map(key=>[key.userId,publicKey(key)]));const calls:{path:string;input:any}[]=[];let ciphertext='',revision=1;const request=async<T,>(path:string,input:any={})=>{calls.push({path,input});if(path.startsWith('/api/e2ee/keys/'))return {key:keys.get(path.split('/').at(-1)!)} as T;if(path==='/api/e2ee/drafts'&&input.method==='POST'){ciphertext=input.body.ciphertext;return {draft:{id:draftId,revision}} as T;}if(path===`/api/e2ee/drafts/${draftId}`){if(input.method==='PUT'){if(input.body.revision!==revision)throw new Error('REVISION_CONFLICT');ciphertext=input.body.ciphertext;revision++;}return {draft:{id:draftId,revision,ciphertext}} as T;}return {message:{messageId:'committed-id',conversationId:'thread-id',duplicate:calls.filter(call=>call.input.method==='POST'&&call.path.endsWith('/messages')).length>1}} as T;};const client=new PhoneMailE2eeClient({apiBaseUrl:'https://app.test',trustStore:pins,request});return {alice,bob,pins,keys,calls,request,client};}
test('approved crypto flow protects text and attachment bytes; sender Sent remains readable',async()=>{const {alice,bob,pins,client,calls}=await fixture();const input={sender:alice,passphrase,to:[bobId],subject:'Secret subject',text:'नमस्ते\nPrivate body',attachments:[new File([new Uint8Array([0,1,255])],'private.bin',{type:'application/octet-stream'})],idempotencyKey:'original-operation-1'};await assert.rejects(client.prepareEncryptedMessage(input),/Verify each recipient/);await pins.set({userId:bobId,fingerprint:bob.fingerprint});const prepared=await client.prepareEncryptedMessage(input);await assert.rejects(client.sendPreparedMessage({...prepared}),/Prepare encrypted/);await client.sendPreparedMessage(prepared);await client.sendPreparedMessage(prepared);const sends=calls.filter(call=>call.path.endsWith('/messages'));assert.deepEqual(sends[0],sends[1]);const body=JSON.stringify(sends[0].input);for(const secret of [input.subject,input.text,'private.bin'])assert.equal(body.includes(secret),false);const recipient=await decryptMime(bob,passphrase,prepared.ciphertext,alice);assert.equal(await decryptMime(alice,passphrase,prepared.ciphertext),recipient);const parsed=decodeMime(recipient);assert.equal(parsed.subject,input.subject);assert.equal(parsed.text,input.text);assert.deepEqual([...parsed.attachments[0].bytes],[0,1,255]);});
test('signed durable restoration preserves exact ciphertext, reply, operation and account across client reload',async()=>{const {alice,bob,pins,client,request,calls}=await fixture();await pins.set({userId:bobId,fingerprint:bob.fingerprint});const original=await client.prepareEncryptedMessage({sender:alice,passphrase,to:[bobId],subject:'private',text:'durable secret',idempotencyKey:'durable-operation-2',replyToId:draftId});await client.sendPreparedMessage(original);const record=await client.exportPrepared(original,alice,passphrase);assert.equal(JSON.stringify(record).includes('durable secret'),false);assert.equal(JSON.stringify(record).includes('PRIVATE KEY'),false);const next=new PhoneMailE2eeClient({apiBaseUrl:'https://app.test',trustStore:pins,request});await assert.rejects(next.sendPreparedMessage(original),/Prepare encrypted/);const restored=await next.restorePrepared(JSON.parse(JSON.stringify(record)),alice);await next.sendPreparedMessage(restored);const sends=calls.filter(call=>call.path.endsWith('/messages'));assert.deepEqual(sends[0],sends[1]);assert.equal(sends[1].input.body.replyToId,draftId);await assert.rejects(next.restorePrepared(record,bob),/another account/);await assert.rejects(next.restorePrepared({...record,prepared:{...record.prepared,idempotencyKey:'tampered-key'}},alice));await assert.rejects(next.restorePrepared({...record,prepared:{...record.prepared,replyToId:aliceId}},alice));await assert.rejects(next.restorePrepared({...record,prepared:{...record.prepared,unexpected:true}},alice));await assert.rejects(next.restorePrepared({...record,createdAt:Date.now()-24*60*60*1000},alice),/retry window ended/);await assert.rejects(client.exportPrepared(original,bob,passphrase),/unprepared/);});
test('cookie request adapter does not request bearer token or invoke legacy fetch',async()=>{const {alice,bob,pins,request}=await fixture();await pins.set({userId:bobId,fingerprint:bob.fingerprint});const client=new PhoneMailE2eeClient({apiBaseUrl:'https://app.test',trustStore:pins,accessToken:()=>{throw new Error('Bearer must not be touched');},fetcher:async()=>{throw new Error('Legacy fetch must not be used');},request});await client.prepareEncryptedMessage({sender:alice,passphrase,to:[bobId],subject:'private',text:'cookie',idempotencyKey:'cookie-transport'});});
test('encrypted revisioned draft restores recipients and sends saved content atomically',async()=>{const {alice,bob,pins,client,request}=await fixture();await pins.set({userId:bobId,fingerprint:bob.fingerprint});const saved=await client.saveEncryptedDraft(alice,passphrase,{subject:'draft',text:'saved body',draftRouting:{to:[bobId],cc:[]}});const stored=await request<{draft:{ciphertext:string}}>(`/api/e2ee/drafts/${draftId}`);const parsed=decodeMime(await decryptMime(alice,passphrase,stored.draft.ciphertext));assert.deepEqual(parsed.to,[bobId]);const updated=await client.updateEncryptedDraft(alice,passphrase,saved.draft.id,1,{subject:'draft 2',text:'latest',draftRouting:{to:[bobId],cc:[]}});assert.equal(updated.draft.revision,2);await assert.rejects(client.updateEncryptedDraft(alice,passphrase,draftId,1,{subject:'stale',text:'stale'}),/REVISION_CONFLICT/);const input={sender:alice,passphrase,to:[bobId],subject:'ignored',text:'ignored',draftId,revision:2,idempotencyKey:'atomic-draft-send'};const prepared=await client.prepareEncryptedDraftSend(input);const content=decodeMime(await decryptMime(bob,passphrase,prepared.ciphertext,alice));assert.equal(content.text,'latest');const record=await client.exportPrepared(prepared,alice,passphrase);const restored=await client.restorePrepared(record,alice);assert.ok('draftId' in restored);await client.sendPreparedDraft(restored);await assert.rejects(client.prepareEncryptedDraftSend({...input,replyToId:aliceId}),/does not support atomic encrypted draft replies/);});
test('strict QR rejects URLs, unknown fields and oversized data; trust requires independent confirmation',async()=>{const {bob,client}=await fixture();const payload=await makeQrPayload(bob);assert.equal((await readQrPayload(payload)).fingerprint,bob.fingerprint);const inspected=await client.inspectQr(payload);await assert.rejects(client.trustQr(inspected,false),/independent trusted channel/);await client.trustQr(inspected,true);for(const value of ['https://evil.test','PHONEMAIL:E2EE:2:e30','x'.repeat(8193),`PHONEMAIL:E2EE:1:${Buffer.from(JSON.stringify({version:1,userId:bobId,fingerprint:bob.fingerprint,url:'https://evil.test'})).toString('base64url')}`])await assert.rejects(readQrPayload(value));});
test('historical independently verified signatures remain readable after key rotation',async()=>{const {alice,bob,pins}=await fixture();const changed=await createIdentity(aliceId,passphrase);const encrypted=await encryptMime([alice,bob],passphrase,{subject:'before rotation',text:'historical'});await pins.set({userId:aliceId,fingerprint:alice.fingerprint});await pins.set({userId:aliceId,fingerprint:changed.fingerprint});const client=new PhoneMailE2eeClient({apiBaseUrl:'https://app.test',trustStore:pins,request:async<T,>(path:string)=>{if(path.endsWith('/history'))return {keys:[publicKey(alice),publicKey(changed)]} as T;return {message:{senderUserId:aliceId,ciphertext:encrypted.ciphertext}} as T;}});assert.equal(decodeMime(await client.decryptMessage(bob,passphrase,draftId)).text,'historical');await pins.remove(aliceId);await assert.rejects(client.decryptMessage(bob,passphrase,draftId),/Verify the sender fingerprint/);});
test('public-key bytes and private backups must match immutable account and fingerprint',async()=>{const [alice,bob]=await identities;await assert.rejects(importIdentity(bobId,alice.encryptedPrivateKey,passphrase),/not bound/);await assert.rejects(importIdentity(aliceId,alice.encryptedPrivateKey,'wrong'));await assert.rejects(validatePublicIdentity({...bob,publicKey:alice.publicKey}),/does not match/);});
test('a decryptable message signed by a different identity fails with the catalog signature error',async()=>{const [alice,bob]=await identities;const encrypted=await encryptMime([alice,bob],passphrase,{subject:'signer mismatch',text:'Do not display before verification'});await assert.rejects(decryptMime(bob,passphrase,encrypted.ciphertext,bob),/Message signature is invalid/);});
