import {localizeSystemMessage,t,formatDateTime,formatNumber,getLocale,pluralKey} from '../../i18n';
import { useEffect, useRef, useState } from 'react';
import { Modal } from '../../components/ui';
import {searchContacts,publicLabel,type Recipient} from '../../lib/recipients';
import { api } from '../../lib/api';
import type { LocalIdentity } from '../../vendor/e2ee';
import type { TrustedQrStatus } from '../../vendor/e2ee/client';
import { discardRejected, getClient, isUnlocked, listPending, lockKeys, readIdentities, rememberIdentity, retryEncrypted, unlockKeys, withActiveIdentity } from './service';
import { readTrust, type PendingEncrypted } from './storage';
import './security.css';
type User={id?:string;userId?:string;email?:string;primaryEmail?:string;hasPassword?:boolean;authMethod?:string};
export default function SecurityPanel({user,onClose}:{user:User;onClose:()=>void}){
 const userId=user.id||user.userId||'';
 const [keys,setKeys]=useState<LocalIdentity[]>([]);const [pins,setPins]=useState<ReturnType<typeof readTrust>>({});const [pending,setPending]=useState<PendingEncrypted[]>([]);
 const [selected,setSelected]=useState('');const [activeFingerprint,setActiveFingerprint]=useState('');const [passphrase,setPassphrase]=useState('');const [password,setPassword]=useState('');
 const [unlocked,setUnlocked]=useState(isUnlocked(userId));const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [notice,setNotice]=useState('');const [backedUp,setBackedUp]=useState(false);
 const [qr,setQr]=useState('');const [qrImage,setQrImage]=useState('');const [includeAddress,setIncludeAddress]=useState(false);const [receivedQr,setReceivedQr]=useState('');const [inspection,setInspection]=useState<TrustedQrStatus>();const [compared,setCompared]=useState(false);
 const [scanning,setScanning]=useState(false);const scanner=useRef<{stop:()=>Promise<unknown>;clear:()=>void}|null>(null);const alive=useRef(true);const closeRef=useRef<HTMLButtonElement>(null);
 const [contactLabels,setContactLabels]=useState<Record<string,Recipient>>({});
 useEffect(()=>{void searchContacts('').then(items=>setContactLabels(Object.fromEntries(items.filter(c=>c.userId).map(c=>[c.userId!,{address:c.address,name:c.label}])))).catch(()=>{})},[userId]);
 const otpOnly=user.hasPassword===false||user.authMethod==='otp';
 async function refresh(){setKeys(readIdentities(userId));setPins(readTrust(userId));setPending(await listPending(userId));setUnlocked(isUnlocked(userId));try{const result=await api<{key:{fingerprint:string}}>(`/e2ee/keys/${userId}`);setActiveFingerprint(result.key.fingerprint);}catch(e){if((e as {status?:number}).status===404)setActiveFingerprint('');else throw e;}}
 useEffect(()=>{alive.current=true;closeRef.current?.focus();refresh().catch(e=>setError(e.message));const lock=()=>setUnlocked(false);window.addEventListener('phonemail:keys-locked',lock);return()=>{alive.current=false;window.removeEventListener('phonemail:keys-locked',lock);const current=scanner.current;scanner.current=null;if(current)void current.stop().catch(()=>{}).then(()=>current.clear());};},[userId]);
 async function action(work:()=>Promise<void>){setBusy(true);setError('');setNotice('');try{await work();await refresh();}catch(e){setError(e instanceof Error?e.message:t("m_dfae71cb7c5b"));}finally{setBusy(false);}}
 async function create(){const client=await getClient(userId);const identity=await client.createIdentity(userId,passphrase);await rememberIdentity(identity,passphrase);setSelected(identity.fingerprint);await client.enroll(identity,passphrase,password);setPassword('');setPassphrase('');setNotice(t("m_b18dbf1a3e77"));}
 async function enroll(){const client=await getClient(userId);const identity=keys.find(key=>key.fingerprint===selected)||keys.at(-1);if(!identity)throw new Error(t("m_4c5051e6dd06"));await client.importIdentity(userId,identity.encryptedPrivateKey,passphrase);await client.enroll(identity,passphrase,password);await rememberIdentity(identity,passphrase);setPassword('');setPassphrase('');setNotice(t("m_157bef267021"));}
 async function rotate(){if(!backedUp)throw new Error(t("m_1f6201a8b8a6"));await withActiveIdentity(userId,async(identity,secret)=>{const client=await getClient(userId);const next=await client.createIdentity(userId,secret);await rememberIdentity(next,secret);await client.rotate(identity,next,secret,password);setSelected(next.fingerprint);});setPassword('');setNotice(t("m_99d010aca44a"));setBackedUp(false);}
 async function revoke(){if(!backedUp)throw new Error(t("m_293c338cbf07"));await withActiveIdentity(userId,async(identity,secret)=>(await getClient(userId)).revoke(identity,secret,password));setPassword('');setNotice(t("m_43874e419886"));}
 async function backup(){const {exportIdentity}=await import('../../vendor/e2ee');if(!keys.length)throw new Error(t("m_8436d7622770"));const result=[];for(const identity of keys)result.push({userId,encryptedPrivateKey:await exportIdentity(identity)});download(JSON.stringify({version:1,userId,keys:result}),'phonemail-encrypted-keys.json','application/json');setNotice(t("m_7444f1421ea1"));}
 async function importBackup(file:File){if(file.size>2*1024*1024)throw new Error(t("m_da73858b5836"));const value=await file.text();const client=await getClient(userId);let entries:string[];if(value.startsWith('-----BEGIN PGP PRIVATE KEY BLOCK-----'))entries=[value];else{const data=JSON.parse(value);if(data.version!==1||data.userId!==userId||!Array.isArray(data.keys)||!data.keys.length||data.keys.length>50)throw new Error(t("m_b1108bf12654"));entries=data.keys.map((item:{userId:string;encryptedPrivateKey:string})=>{if(item.userId!==userId||typeof item.encryptedPrivateKey!=='string')throw new Error(t("m_f79462a3f18e"));return item.encryptedPrivateKey;});}for(const entry of entries){const identity=await client.importIdentity(userId,entry,passphrase);await rememberIdentity(identity,passphrase);setSelected(identity.fingerprint);}setPassphrase('');setNotice(t("m_e1b3f3e81423"));}
 async function showQr(){const identity=keys.find(key=>key.fingerprint===(selected||activeFingerprint))||keys.at(-1);if(!identity)throw new Error(t("m_8adc53bcc85a"));const {makeQrPayload}=await import('../../vendor/e2ee');const payload=await makeQrPayload(identity,includeAddress?(user.primaryEmail||user.email):undefined);const {renderIdentityQr}=await import('./qr');setQr(payload);setQrImage(await renderIdentityQr(payload));}
 async function inspect(payload=receivedQr){setInspection(undefined);setCompared(false);const status=await(await getClient(userId)).inspectQr(payload.trim());setInspection(status);setReceivedQr('');setNotice(t("m_544334a22113"));}
 async function stopScanner(){const current=scanner.current;scanner.current=null;if(current){await current.stop().catch(()=>{});current.clear();}setScanning(false);}
 async function startScanner(){if(!window.isSecureContext||!navigator.mediaDevices?.getUserMedia)throw new Error(t("m_1852a665904d"));const {Html5Qrcode}=await import('html5-qrcode');setScanning(true);const reader=new Html5Qrcode('security-qr-reader');scanner.current=reader;try{await reader.start({facingMode:'environment'},{fps:5,qrbox:{width:230,height:230}},text=>{if(!alive.current)return;setReceivedQr(text);void stopScanner();void action(()=>inspect(text));},()=>{});}catch(e){await stopScanner();throw e;}}
 return <Modal title={t("m_ad5f9680d298")} onClose={()=>{if(!busy)onClose()}} wide busy={busy}><section className="security-panel" aria-labelledby="security-title">
 <header className="panel-heading"><div><p className="eyebrow">{t("m_adc5a15b1687")}</p><h2 id="security-title">{t("m_ad5f9680d298")}</h2></div><button ref={closeRef} disabled={busy} type="button" className="button secondary" onClick={onClose}>{t("m_7d9eb7acb13e")}</button></header>
 <p className="security-intro">{t("m_287613d8dc56")}</p>
 {error&&<p className="error" role="alert">{localizeSystemMessage(error)}</p>}{notice&&<p className="status-message" role="status">{localizeSystemMessage(notice)}</p>}
 <div className="security-section"><h3>{t("m_0de9881822b9")}<span className="status-pill">{unlocked?t("m_531c7b28abf2"):t("m_a424e33d9093")}</span></h3><p className="muted">{t("m_c54ede3c793a")}</p>
 <p className="fingerprint"><strong>{t("m_7e1b0d5641f2")}</strong> {user.primaryEmail||user.email||t('recipient.unknown')}</p><label>{t("m_c917591c8632")}<select value={selected} onChange={event=>setSelected(event.target.value)}><option value="">{t("m_bb1c56615eb0")}</option>{keys.map(key=><option key={key.fingerprint} value={key.fingerprint}>{key.fingerprint===activeFingerprint?t("m_5a626267473b"):t("m_7b0e55802cac")}{key.fingerprint.slice(-16)}</option>)}</select></label>
 {keys.map(key=><div className="key-row" key={key.fingerprint}><span>{key.fingerprint===activeFingerprint?t("m_2ca8bacd2512"):t("m_c68014504390")}</span><code className="fingerprint">{key.fingerprint.match(/.{1,4}/g)?.join(' ')}</code></div>)}
 <label>{t("m_6e2495ba1a86")}<input type="password" autoComplete="off" value={passphrase} onChange={event=>setPassphrase(event.target.value)} minLength={12} placeholder={t("m_dcbce242a08f")}/></label>
 <div className="button-row"><button className="button" disabled={busy||!passphrase||!keys.length} onClick={()=>action(async()=>{await unlockKeys(userId,passphrase);setPassphrase('');setNotice(t("m_e00bf38cd45e"));})}>{t("m_e9b748348752")}</button><button className="button secondary" disabled={!unlocked} onClick={()=>{lockKeys();setUnlocked(false);setNotice(t("m_5aecd754f8df"));}}>{t("m_93ba3f249e56")}</button><button className="button secondary" disabled={busy||!keys.length} onClick={()=>action(backup)}>{t("m_0a729b90dd32")}</button></div>
 <label className="file-label">{t("m_b20c54d0f810")}<input type="file" accept=".asc,.json,application/json" disabled={busy||!passphrase} onChange={event=>{const file=event.target.files?.[0];event.target.value='';if(file)void action(()=>importBackup(file));}}/></label>
 <p className="muted">{t("m_1fb2f24dd23b")}</p></div>
 <div className="security-section"><h3>{t("m_c59145aec40a")}</h3>{otpOnly?<p className="notice">{t("m_76ecf956bd04")}</p>:<p className="muted">{t("m_5c9a61e05daa")}</p>}
 <label>{t("m_7da69e0ebd60")}<input type="password" autoComplete="current-password" value={password} onChange={event=>setPassword(event.target.value)} disabled={otpOnly}/></label>
 <div className="button-row"><button className="button" disabled={busy||otpOnly||!password||passphrase.length<12||!!activeFingerprint} onClick={()=>action(create)}>{t("m_4a5b1d2f888a")}</button><button className="button secondary" disabled={busy||otpOnly||!password||!passphrase||!keys.length||!!activeFingerprint} onClick={()=>action(enroll)}>{t("m_1ea482b41996")}</button></div>
 <label className="check-row"><input type="checkbox" checked={backedUp} onChange={event=>setBackedUp(event.target.checked)}/>{t("m_6dc281af1d59")}</label>
 <div className="button-row"><button className="button secondary" disabled={busy||otpOnly||!password||!unlocked||!activeFingerprint||!backedUp} onClick={()=>action(rotate)}>{t("m_220c74869166")}</button><button className="button danger" disabled={busy||otpOnly||!password||!unlocked||!activeFingerprint||!backedUp} onClick={()=>action(revoke)}>{t("m_d4ccc02f76c9")}</button></div></div>
 <div className="security-section"><h3>{t("m_f197e0e64211")}</h3><label className="check-row"><input type="checkbox" checked={includeAddress} onChange={event=>setIncludeAddress(event.target.checked)}/>{t("m_f819d2829e00")}</label><button className="button secondary" disabled={busy||!keys.length} onClick={()=>action(showQr)}>{t("m_6ab2df4b7b97")}</button>{qrImage&&<div className="qr-display"><img src={qrImage} alt={t("m_06ebf9d47c38")} width="250" height="250"/><button className="button secondary" onClick={()=>download(qr,'phonemail-identity.json','application/json')}>{t('identity.export')}</button></div>}</div>
 <div className="security-section"><h3>{t("m_e4c060543034")}</h3><p className="muted">{t("m_ff2f7c43f858")}</p><label>{t("m_313a4e352785")}<textarea value={receivedQr} style={{WebkitTextSecurity:"disc"} as React.CSSProperties} maxLength={8192} onChange={event=>{setReceivedQr(event.target.value);setInspection(undefined);setCompared(false);}} placeholder={t("m_d6420500d445")} rows={4}/></label><div className="button-row"><button className="button" disabled={busy||!receivedQr} onClick={()=>action(()=>inspect())}>{t("m_b56b64b100c0")}</button><button className="button secondary" disabled={busy} onClick={()=>action(scanning?stopScanner:startScanner)}>{scanning?t("m_c2e8e6cf5611"):t("m_eb0d1e3cda68")}</button></div><label className="file-label">{t("m_2081eafe3f04")}<input type="file" accept="image/*" disabled={busy} onChange={event=>{const file=event.target.files?.[0];event.target.value='';if(file)void action(async()=>{const {decodeIdentityQrImage}=await import('./qr');const payload=await decodeIdentityQrImage(file);setReceivedQr(payload);await inspect(payload);});}}/></label><div id="security-qr-reader" aria-label={t("m_0f14b1c54b30")}/>
 {inspection&&<div className="trust-review"><p>{inspection.trust==='fingerprint-mismatch'?t("m_6069f2199e17"):t("m_23a8e19a22f5")}</p><p>{publicLabel(contactLabels[inspection.identity.userId]||{})}</p>{inspection.identity.address&&<p>{t('identity.claim',{address:inspection.identity.address})}</p>}<code className="fingerprint">{inspection.identity.fingerprint.match(/.{1,4}/g)?.join(' ')}</code><label className="check-row"><input type="checkbox" checked={compared} onChange={event=>setCompared(event.target.checked)}/>{t("m_0f6d225ef021")}</label><button className="button" disabled={busy||!compared} onClick={()=>action(async()=>{await(await getClient(userId)).trustQr(inspection,compared);setInspection(undefined);setCompared(false);setNotice(t("m_d0235c9dbf4c"));})}>{t("m_bff8fee47e0b")}</button></div>}
 {Object.entries(pins).map(([id,history])=><div className="trust-row" key={id}><div><p>{publicLabel(contactLabels[id]||{})}</p><code className="fingerprint">{history.at(-1)?.fingerprint}</code><p className="muted">{pluralKey(history.length,'m_d29723f188a7','m_f1914e862a86')}</p></div><button className="button secondary" disabled={busy} onClick={()=>action(async()=>{await(await getClient(userId)).removeTrust(id);setNotice(t("m_3a1c1bf09c06"));})}>{t("m_663e1a5bd52f")}</button></div>)}</div>
 <div className="security-section"><h3>{t("m_bf265061cffe")}</h3><p className="muted">{t("m_c252e230572f")}</p>{!pending.length&&<p>{t("m_4ae3e092e304")}</p>}{pending.map(item=><div className="pending-row" key={item.id}><div><strong>{item.state==='unknown'?t("m_929dcffc93cc"):item.state==='failed'?t("m_4ff5b1edbe7d"):t("m_5a0ef1a439f3")}</strong><p>{formatDateTime(item.record.createdAt)}</p>{item.error&&<p className="muted">{item.error}</p>}</div><div className="button-row"><button className="button secondary" disabled={busy} onClick={()=>action(async()=>{await retryEncrypted(userId,item.id);setNotice(t("m_f95b96b6c762"));})}>{t("m_c02ac84b48ce")}</button>{item.state==='failed'&&<button className="button secondary" disabled={busy} onClick={()=>action(()=>discardRejected(userId,item.id))}>{t("m_ce80d7ddbeae")}</button>}</div></div>)}</div>
 </section></Modal>;
}
function download(text:string,name:string,type:string){const url=URL.createObjectURL(new Blob([text],{type}));const link=document.createElement('a');link.href=url;link.download=name;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
