import {t} from '../../i18n';
import { api, ApiError, subscribeSession, withBrowserLock } from '../../lib/api';
import type { LocalIdentity } from '../../vendor/e2ee';
import type { PhoneMailE2eeClient } from '../../vendor/e2ee/client';
import { listPending, putPending, readIdentities, removePending, saveIdentity, trustStore, type PendingEncrypted } from './storage';
import { decodeMime } from './mime';
export { listPending, readIdentities } from './storage';
export type { DecodedMail } from './mime';
type Unlocked = {identity:LocalIdentity; passphrase:string};
let account:string|undefined;
let unlocked:Unlocked[]=[];
const clients=new Map<string,PhoneMailE2eeClient>();
export function lockKeys(){unlocked=[];account=undefined;clients.clear();if(typeof window!=='undefined')window.dispatchEvent(new Event('phonemail:keys-locked'));}
subscribeSession(state=>{if(state==='invalid')lockKeys();});
export function isUnlocked(userId:string){return account===userId&&unlocked.length>0;}
export async function unlockKeys(userId:string,passphrase:string){lockKeys();const {importIdentity}=await import('../../vendor/e2ee');const keys=readIdentities(userId);if(!keys.length)throw new Error(t("m_60b2527aeb51"));const valid:Unlocked[]=[];for(const key of keys){try{valid.push({identity:await importIdentity(userId,key.encryptedPrivateKey,passphrase),passphrase});}catch{/* A historical key may have another passphrase. */}}if(!valid.length)throw new Error(t("m_30469b0c1301"));account=userId;unlocked=valid;return valid.map(item=>item.identity);}
export async function rememberIdentity(identity:LocalIdentity,passphrase:string){if(!window.isSecureContext||!crypto.subtle)throw new Error(t("m_c9b41e9e5246"));const {importIdentity,exportIdentity}=await import('../../vendor/e2ee');const checked=await importIdentity(identity.userId,await exportIdentity(identity),passphrase);saveIdentity(checked);if(account!==identity.userId)lockKeys();account=identity.userId;unlocked=[...unlocked.filter(item=>item.identity.fingerprint!==checked.fingerprint),{identity:checked,passphrase}];}
export async function getClient(userId:string){if(clients.has(userId))return clients.get(userId)!;const {PhoneMailE2eeClient,E2eeClientError}=await import('../../vendor/e2ee/client');const client=new PhoneMailE2eeClient({apiBaseUrl:window.location.origin,trustStore:trustStore(userId),request:async<T,>(path:string,input:{method?:string;body?:unknown;idempotencyKey?:string})=>{try{return await api<T>(path,{method:input.method,body:input.body,headers:input.idempotencyKey?{'Idempotency-Key':input.idempotencyKey}:undefined});}catch(error){if(error instanceof ApiError){const code=error.status===0?'NETWORK_ERROR':error.status===401?'AUTHENTICATION_FAILED':error.code==='REAUTH_REQUIRED'?'REAUTHENTICATION_REQUIRED':error.code==='E2EE_KEY_CHANGED'?'KEY_CHANGED':error.code==='E2EE_KEY_REQUIRED'?'RECIPIENT_KEY_MISSING':error.code==='IDEMPOTENCY_CONFLICT'?'IDEMPOTENCY_CONFLICT':error.code==='REVISION_CONFLICT'?'REVISION_CONFLICT':'REQUEST_REJECTED';throw new E2eeClientError(code,error.message,error.status);}throw error;}}});clients.set(userId,client);return client;}
function available(userId:string){if(!isUnlocked(userId))throw new Error(t("m_dd252ca7d4d5"));return unlocked;}
async function active(userId:string){const keys=available(userId);const {key}=await api<{key:{fingerprint:string}}>(`/e2ee/keys/${userId}`);const selected=keys.find(item=>item.identity.fingerprint===key.fingerprint.toUpperCase());if(!selected)throw new Error(t("m_7e7a4393b5f4"));return selected;}
export async function withActiveIdentity<T>(userId:string,action:(identity:LocalIdentity,passphrase:string)=>Promise<T>){const item=await active(userId);return action(item.identity,item.passphrase);}
export type EncryptedCompose={userId:string;to:string[];cc?:string[];subject:string;text:string;attachments?:File[];replyToId?:string;draftId?:string;revision?:number};
export async function sendEncrypted(input:EncryptedCompose){return withBrowserLock(`e2ee-send:${input.userId}`,async()=>{const pending=await listPending(input.userId);if(pending.some(item=>item.state!=='failed'))throw new Error(t("m_1e529b3ed2df"));const {identity,passphrase}=await active(input.userId);const client=await getClient(input.userId);const message={...input,sender:identity,passphrase,idempotencyKey:crypto.randomUUID()};const prepared=input.draftId?await client.prepareEncryptedDraftSend({...message,draftId:input.draftId,revision:input.revision!}):await client.prepareEncryptedMessage(message);const record=await client.exportPrepared(prepared,identity,passphrase);const operation:PendingEncrypted={id:`${input.userId}:${prepared.idempotencyKey}`,userId:input.userId,record,state:'queued'};await putPending(operation);return deliver(operation,identity);});}
async function deliver(operation:PendingEncrypted,identity:LocalIdentity){const client=await getClient(operation.userId);const prepared=await client.restorePrepared(operation.record,identity);try{const response='draftId' in prepared?await client.sendPreparedDraft(prepared):await client.sendPreparedMessage(prepared);await removePending(operation.userId,operation.id);return response;}catch(error){const status=(error as {status?:number}).status;operation.state=operation.state==='unknown'||!status||status>=500||(error as {code?:string}).code==='IDEMPOTENCY_CONFLICT'?'unknown':'failed';operation.error=error instanceof Error?error.message:t("m_17bb484922e7");await putPending(operation);throw new Error(operation.state==='unknown'?t("m_ef74fba7f284"):operation.error);}}
export async function retryEncrypted(userId:string,id:string){return withBrowserLock(`e2ee-send:${userId}`,async()=>{
  const operation=(await listPending(userId)).find(item=>item.id===id);if(!operation)throw new Error(t("m_c6e6e1c3e029"));
  // Lookup supports e2ee_message too. Reconcile before attempting any replay, including expired records.
  try {
    const result=await api<{operation:{resourceType:string;resourceId:string}}>(`/conversations/operations/${encodeURIComponent(operation.record.prepared.idempotencyKey)}`);
    if(result.operation.resourceType!=='e2ee_message')throw new Error(t("m_58be4f12e30d"));
    const {message}=await api<{message:{id:string;conversationId:string;senderUserId:string;ciphertext:string}}>(`/e2ee/messages/${result.operation.resourceId}`);
    if(message.senderUserId!==userId||message.ciphertext!==operation.record.prepared.ciphertext)throw new Error(t("m_4095b142328a"));
    await removePending(userId,id);return {message:{messageId:message.id,conversationId:message.conversationId,duplicate:true}};
  } catch(error) { if(!(error instanceof ApiError)||error.status!==404)throw error; }
  const key=available(userId).find(item=>item.identity.fingerprint===operation.record.fingerprint);if(!key)throw new Error(t("m_e2b0eaabeab9"));return deliver(operation,key.identity);
});}
export async function discardRejected(userId:string,id:string){const item=(await listPending(userId)).find(item=>item.id===id);if(!item||item.state!=='failed')throw new Error(t("m_392939cfeed7"));return removePending(userId,id);}
export async function decryptMessage(userId:string,id:string){const keys=available(userId);const client=await getClient(userId);let last:unknown;for(const key of [...keys].reverse()){try{return decodeMime(await client.decryptMessage(key.identity,key.passphrase,id));}catch(error){last=error;}}throw last;}
export async function saveEncryptedDraft(userId:string,content:{to:string[];cc?:string[];subject:string;text:string;attachments?:File[]},existing?:{id:string;revision:number}){const {identity,passphrase}=await active(userId);const client=await getClient(userId);const inner={...content,draftRouting:{to:content.to,cc:content.cc??[]}};return existing?client.updateEncryptedDraft(identity,passphrase,existing.id,existing.revision,inner):client.saveEncryptedDraft(identity,passphrase,inner);}
export async function loadEncryptedDraft(userId:string,id:string){const keys=available(userId);const response=await api<{draft:{id:string;revision:number;ciphertext:string}}>(`/e2ee/drafts/${id}`);const {decryptMime}=await import('../../vendor/e2ee');let last:unknown;for(const key of [...keys].reverse()){try{return {...decodeMime(await decryptMime(key.identity,key.passphrase,response.draft.ciphertext)),id:response.draft.id,revision:response.draft.revision};}catch(error){last=error;}}throw last;}
