import {t} from '../../i18n';
import type { LocalIdentity } from '../../vendor/e2ee';
import type { StoredTrust, FingerprintTrustStore } from '../../vendor/e2ee/client';
import type { DurablePrepared } from '../../vendor/e2ee/durable';
const UUID=/^[a-f0-9]{8}-[a-f0-9]{4}-[1-8][a-f0-9]{3}-[89ab][a-f0-9]{3}-[a-f0-9]{12}$/i;
function prefix(userId:string) {if(!UUID.test(userId))throw new Error(t("m_769f53433f49"));return `phonemail.secure.v1:${userId.toLowerCase()}:`;}
export function readIdentities(userId:string):LocalIdentity[] {const raw=localStorage.getItem(prefix(userId)+'keys');if(!raw)return [];const items:unknown=JSON.parse(raw);if(!Array.isArray(items)||items.length>50)throw new Error(t("m_1b254d1233dc"));return items.filter((item):item is LocalIdentity=>!!item&&item.userId===userId&&typeof item.fingerprint==='string'&&typeof item.publicKey==='string'&&typeof item.encryptedPrivateKey==='string'&&item.encryptedPrivateKey.length<=32768);}
export function saveIdentity(identity:LocalIdentity) {const keys=readIdentities(identity.userId).filter(key=>key.fingerprint!==identity.fingerprint);if(keys.length>=50)throw new Error(t("m_c3267410f5c3"));keys.push(identity);localStorage.setItem(prefix(identity.userId)+'keys',JSON.stringify(keys));}
export function readTrust(userId:string):Record<string,StoredTrust[]> {const raw=localStorage.getItem(prefix(userId)+'trust');if(!raw)return {};const parsed=JSON.parse(raw);if(!parsed||typeof parsed!=='object'||Array.isArray(parsed))throw new Error(t("m_d188abe42150"));return parsed;}
export function trustStore(userId:string):FingerprintTrustStore {
 return {async get(id){return readTrust(userId)[id]?.at(-1);},async getHistory(id){return readTrust(userId)[id]||[];},async set(trust){const pins=readTrust(userId);const old=pins[trust.userId]||[];pins[trust.userId]=[...old.filter(pin=>pin.fingerprint!==trust.fingerprint),trust].slice(-50);localStorage.setItem(prefix(userId)+'trust',JSON.stringify(pins));},async remove(id){const pins=readTrust(userId);delete pins[id];localStorage.setItem(prefix(userId)+'trust',JSON.stringify(pins));}};
}
export type PendingEncrypted={id:string;userId:string;record:DurablePrepared;state:'queued'|'unknown'|'failed';error?:string};
async function db(){return new Promise<IDBDatabase>((resolve,reject)=>{const req=indexedDB.open('phonemail-encrypted-outbox-v1',1);req.onupgradeneeded=()=>req.result.createObjectStore('operations',{keyPath:'id'});req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(new Error(t("m_710cc69457d8")));});}
async function transact<T>(mode:IDBTransactionMode,run:(store:IDBObjectStore)=>IDBRequest<T>):Promise<T>{const database=await db();return new Promise((resolve,reject)=>{const tx=database.transaction('operations',mode);let result:T;const request=run(tx.objectStore('operations'));request.onsuccess=()=>{result=request.result;};tx.oncomplete=()=>{database.close();resolve(result);};tx.onabort=tx.onerror=()=>{database.close();reject(new Error(t("m_28f5a56b31d0")));};});}
export async function listPending(userId:string){const records=await transact('readonly',store=>store.getAll());return (records as PendingEncrypted[]).filter(item=>item.userId===userId);}
export async function putPending(item:PendingEncrypted){prefix(item.userId);const records=await listPending(item.userId);if(!records.some(r=>r.id===item.id)&&records.length>=20)throw new Error(t("m_20f8a9332355"));if(records.filter(r=>r.id!==item.id).reduce((sum,r)=>sum+r.record.prepared.ciphertext.length,0)+item.record.prepared.ciphertext.length>32*1024*1024)throw new Error(t("m_1f24074a45d1"));await transact('readwrite',store=>store.put(item));}
export async function removePending(userId:string,id:string){const match=(await listPending(userId)).find(item=>item.id===id);if(!match)throw new Error(t("m_2f186ad03992"));await transact('readwrite',store=>store.delete(id));}
